# Generated by Django 5.1.6 on 2025-08-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frauddetectionrule',
            name='rule_type',
            field=models.CharField(choices=[('VELOCITY', 'Transaction Velocity'), ('AMOUNT_ANOMALY', 'Amount Anomaly'), ('AMOUNT_THRESHOLD', 'Amount Threshold'), ('LOCATION_ANOMALY', 'Location Anomaly'), ('PATTERN_ANOMALY', 'Pattern Anomaly'), ('TIME_ANOMALY', 'Time Anomaly'), ('MERCHANT_RISK', 'Merchant Risk'), ('BEHAVIORAL', 'Behavioral Analysis'), ('ML_MODEL', 'Machine Learning Model')], max_length=20),
        ),
    ]
